### ISSUE TITLE
Passing Props to Components in Stepper

### ISSUE THREAD

**Issue by arturgithub** [beanloop/react-step#1]
Hi there, first of all thank you for sharing the project, I think this complements perfectly react-toolbox.

I would like to know if there is a way of passing prps to the components within the stepper:

```
<Stepper pages={[
  {
    component: PageOne,
  },
  {
    component: PageTwo,
  },
  {
    component: PageThree,
  },
]}>
```

In my case I would like to define "PageOne", "PageTwo" and "PageThree" also with props... 

Thanks for the response and apologies if it is something very easy that should be known.

**Comment by drager** [comment]
Hey! Glad that you like it.

You can use `render` over `component`:
```javascript
<Stepper pages={[
  {
    render: () => <PageOne myProp='Hello' />,
  },
]}>
```

**Comment by arturgithub** [comment]
Thanks!! I forgot to answered you!
