### ISSUE TITLE
VerticalStepper not found

### ISSUE THREAD

**Issue by galileoguzman** [beanloop/react-step#4]
I have installed `react-step` but when I try to use / implement a vertical stepper I get this error:

`'VerticalStepper' was not found in 'react-step'`

I am importing it with this

`import { Stepper, StepperView, VerticalStepper, AdvanceButton, ReverseButton, DotTracker } from 'react-step';`

I used `react-toolbox` but got an error about another library. Can you show me how should I implement the  **VerticalStepper** component

**Comment by drager** [comment]
Hey @galileoguzman!

We had to change the name of this package due to package hijacking. So the package you should install is [react-steppers](https://www.npmjs.com/package/react-steppers). Please let me know if you got any problems with it.

**Comment by galileoguzman** [comment]
Resolved, thanks man!

**Comment by galileoguzman** [comment]
BTW I used this

```
import { Stepper, withStepper } from 'react-step';
import { VerticalStepper } from 'react-step/react-toolbox'
```
And the component with this:

```
<Stepper allowJumpAhead={allowJumpAhead} pages={pages}>
        {verticalStepper && <VerticalStepper activeColor="#64a6f4" canAdvance={false} canReverse={false} />}
</Stepper>
```

Note: wrapped on another component.

**Comment by drager** [comment]
@galileoguzman Are you importing from 'react-steppers' now? Can I close this issue? :)

**Comment by galileoguzman** [comment]
You can close it

**Comment by galileoguzman** [comment]
Just a question for you, Is there a way to change the icons ?

**Comment by drager** [comment]
You mean the vertical stepper's icons, that renders when status is set to `alert` or `done`? No, it's not possible to change those at the moment. I'm closing this now but feel free to open another issue/pull request to discuss the icons further.
